### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by teto** [iluxonchik/rfc-bibtex#7]
Thanks for the tool !
I am trying to package it for www.nixos.org, and I just wonder what's the code licence ?
Ty

**Comment by iluxonchik** [comment]
Hello @teto, I will add an MIT licence now.

I wrote this tool in a few hours, because I had a lot of `RFC`'s to cite in my master thesis. If you're going to be adding this to a Linux distro, I will surely add some more tests and tidy up the code. 

If you have any suggestions/requests, let me know!

**Comment by simsong** [comment]
I recommend MIT License. It's easy.

**Comment by iluxonchik** [comment]
> I recommend MIT License. It's easy.

Yes, I already added it yesterday :smile:

I'm going to close this issue for now.

**Comment by teto** [comment]
thanks. Would be cool rfc-bibtex -help to show an actual example for "inline_args"
```
 inline_args           list of RFC and/or Internet-Draft IDs, in any order
like "RFC5246 draft-ietf-tls-tls13-21"
```

**Comment by teto** [comment]
Added to nixos in https://github.com/NixOS/nixpkgs/pull/48198 .

**Comment by iluxonchik** [comment]
> Added to nixos in [NixOS/nixpkgs#48198](https://github.com/NixOS/nixpkgs/pull/48198) .

Great :smile: I will work on the improvements that me, you and @simsong  discussed in a few days. Absolutely overloaded with work now.
